In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Breast_Cancer.csv')
data

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,Other,Married,T1,N1,IIA,Moderately differentiated,2,Regional,9,Positive,Positive,1,1,49,Alive
4020,56,White,Divorced,T2,N2,IIIA,Moderately differentiated,2,Regional,46,Positive,Positive,14,8,69,Alive
4021,68,White,Married,T2,N1,IIB,Moderately differentiated,2,Regional,22,Positive,Negative,11,3,69,Alive
4022,58,Black,Divorced,T2,N1,IIB,Moderately differentiated,2,Regional,44,Positive,Positive,11,1,72,Alive
4023,46,White,Married,T2,N1,IIB,Moderately differentiated,2,Regional,30,Positive,Positive,7,2,100,Alive

In [3]:
data.isnull().sum()

Age                       0
Race                      0
Marital Status            0
T Stage                   0
N Stage                   0
6th Stage                 0
differentiate             0
Grade                     0
A Stage                   0
Tumor Size                0
Estrogen Status           0
Progesterone Status       0
Regional Node Examined    0
Reginol Node Positive     0
Survival Months           0
Status                    0
dtype: int64

In [4]:
data.dtypes

Age                        int64
Race                      object
Marital Status            object
T Stage                   object
N Stage                   object
6th Stage                 object
differentiate             object
Grade                     object
A Stage                   object
Tumor Size                 int64
Estrogen Status           object
Progesterone Status       object
Regional Node Examined     int64
Reginol Node Positive      int64
Survival Months            int64
Status                    object
dtype: object

In [26]:
from sklearn.preprocessing import LabelEncoder

lab_enc = LabelEncoder()

df_1 = data.copy()
df_1['Race'] = lab_enc.fit_transform(df_1['Race'])
df_1

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,2,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,2,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,2,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,2,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,2,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,1,Married,T1,N1,IIA,Moderately differentiated,2,Regional,9,Positive,Positive,1,1,49,Alive
4020,56,2,Divorced,T2,N2,IIIA,Moderately differentiated,2,Regional,46,Positive,Positive,14,8,69,Alive
4021,68,2,Married,T2,N1,IIB,Moderately differentiated,2,Regional,22,Positive,Negative,11,3,69,Alive
4022,58,0,Divorced,T2,N1,IIB,Moderately differentiated,2,Regional,44,Positive,Positive,11,1,72,Alive
4023,46,2,Married,T2,N1,IIB,Moderately differentiated,2,Regional,30,Positive,Positive,7,2,100,Alive

In [27]:
df_1['Marital Status'] = lab_enc.fit_transform(df_1['Marital Status'])
df_1.dtypes

Age                        int64
Race                       int32
Marital Status             int32
T Stage                   object
N Stage                   object
6th Stage                 object
differentiate             object
Grade                     object
A Stage                   object
Tumor Size                 int64
Estrogen Status           object
Progesterone Status       object
Regional Node Examined     int64
Reginol Node Positive      int64
Survival Months            int64
Status                    object
dtype: object

In [28]:
df_1

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,2,1,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,2,1,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,2,0,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,2,1,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,2,1,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,1,1,T1,N1,IIA,Moderately differentiated,2,Regional,9,Positive,Positive,1,1,49,Alive
4020,56,2,0,T2,N2,IIIA,Moderately differentiated,2,Regional,46,Positive,Positive,14,8,69,Alive
4021,68,2,1,T2,N1,IIB,Moderately differentiated,2,Regional,22,Positive,Negative,11,3,69,Alive
4022,58,0,0,T2,N1,IIB,Moderately differentiated,2,Regional,44,Positive,Positive,11,1,72,Alive
4023,46,2,1,T2,N1,IIB,Moderately differentiated,2,Regional,30,Positive,Positive,7,2,100,Alive

In [29]:
df_1.dtypes

Age                        int64
Race                       int32
Marital Status             int32
T Stage                   object
N Stage                   object
6th Stage                 object
differentiate             object
Grade                     object
A Stage                   object
Tumor Size                 int64
Estrogen Status           object
Progesterone Status       object
Regional Node Examined     int64
Reginol Node Positive      int64
Survival Months            int64
Status                    object
dtype: object

In [34]:
df_1['T Stage '] = lab_enc.fit_transform(df_1['T Stage '])

In [37]:
df_1['N Stage'] = lab_enc.fit_transform(df_1['N Stage'])

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,2,1,0,0,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,2,1,1,1,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,2,0,2,2,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,2,1,0,0,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,2,1,1,0,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,1,1,0,0,IIA,Moderately differentiated,2,Regional,9,Positive,Positive,1,1,49,Alive
4020,56,2,0,1,1,IIIA,Moderately differentiated,2,Regional,46,Positive,Positive,14,8,69,Alive
4021,68,2,1,1,0,IIB,Moderately differentiated,2,Regional,22,Positive,Negative,11,3,69,Alive
4022,58,0,0,1,0,IIB,Moderately differentiated,2,Regional,44,Positive,Positive,11,1,72,Alive
4023,46,2,1,1,0,IIB,Moderately differentiated,2,Regional,30,Positive,Positive,7,2,100,Alive

In [38]:
df_1.dtypes

Age                        int64
Race                       int32
Marital Status             int32
T Stage                    int32
N Stage                    int32
6th Stage                 object
differentiate             object
Grade                     object
A Stage                   object
Tumor Size                 int64
Estrogen Status           object
Progesterone Status       object
Regional Node Examined     int64
Reginol Node Positive      int64
Survival Months            int64
Status                    object
dtype: object

In [39]:
df_1['6th Stage'] = lab_enc.fit_transform(df_1['6th Stage'])
df_1

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,2,1,0,0,0,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,2,1,1,1,2,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,2,0,2,2,4,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,2,1,0,0,0,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,2,1,1,0,1,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,1,1,0,0,0,Moderately differentiated,2,Regional,9,Positive,Positive,1,1,49,Alive
4020,56,2,0,1,1,2,Moderately differentiated,2,Regional,46,Positive,Positive,14,8,69,Alive
4021,68,2,1,1,0,1,Moderately differentiated,2,Regional,22,Positive,Negative,11,3,69,Alive
4022,58,0,0,1,0,1,Moderately differentiated,2,Regional,44,Positive,Positive,11,1,72,Alive
4023,46,2,1,1,0,1,Moderately differentiated,2,Regional,30,Positive,Positive,7,2,100,Alive

In [41]:
df_1['differentiate'] = lab_enc.fit_transform(df_1['differentiate'])
df_1

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,2,1,0,0,0,1,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,2,1,1,1,2,0,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,2,0,2,2,4,0,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,2,1,0,0,0,1,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,2,1,1,0,1,1,3,Regional,41,Positive,Positive,3,1,50,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,1,1,0,0,0,0,2,Regional,9,Positive,Positive,1,1,49,Alive
4020,56,2,0,1,1,2,0,2,Regional,46,Positive,Positive,14,8,69,Alive
4021,68,2,1,1,0,1,0,2,Regional,22,Positive,Negative,11,3,69,Alive
4022,58,0,0,1,0,1,0,2,Regional,44,Positive,Positive,11,1,72,Alive
4023,46,2,1,1,0,1,0,2,Regional,30,Positive,Positive,7,2,100,Alive

In [43]:
df_1['A Stage'] = lab_enc.fit_transform(df_1['A Stage'])
df_1

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,2,1,0,0,0,1,3,1,4,Positive,Positive,24,1,60,Alive
1,50,2,1,1,1,2,0,2,1,35,Positive,Positive,14,5,62,Alive
2,58,2,0,2,2,4,0,2,1,63,Positive,Positive,14,7,75,Alive
3,58,2,1,0,0,0,1,3,1,18,Positive,Positive,2,1,84,Alive
4,47,2,1,1,0,1,1,3,1,41,Positive,Positive,3,1,50,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,1,1,0,0,0,0,2,1,9,Positive,Positive,1,1,49,Alive
4020,56,2,0,1,1,2,0,2,1,46,Positive,Positive,14,8,69,Alive
4021,68,2,1,1,0,1,0,2,1,22,Positive,Negative,11,3,69,Alive
4022,58,0,0,1,0,1,0,2,1,44,Positive,Positive,11,1,72,Alive
4023,46,2,1,1,0,1,0,2,1,30,Positive,Positive,7,2,100,Alive

In [44]:
df_1['Estrogen Status'] = lab_enc.fit_transform(df_1['Estrogen Status'])
df_1

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,2,1,0,0,0,1,3,1,4,1,Positive,24,1,60,Alive
1,50,2,1,1,1,2,0,2,1,35,1,Positive,14,5,62,Alive
2,58,2,0,2,2,4,0,2,1,63,1,Positive,14,7,75,Alive
3,58,2,1,0,0,0,1,3,1,18,1,Positive,2,1,84,Alive
4,47,2,1,1,0,1,1,3,1,41,1,Positive,3,1,50,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,1,1,0,0,0,0,2,1,9,1,Positive,1,1,49,Alive
4020,56,2,0,1,1,2,0,2,1,46,1,Positive,14,8,69,Alive
4021,68,2,1,1,0,1,0,2,1,22,1,Negative,11,3,69,Alive
4022,58,0,0,1,0,1,0,2,1,44,1,Positive,11,1,72,Alive
4023,46,2,1,1,0,1,0,2,1,30,1,Positive,7,2,100,Alive

In [45]:
df_1['Progesterone Status'] = lab_enc.fit_transform(df_1['Progesterone Status'])
df_1

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,2,1,0,0,0,1,3,1,4,1,1,24,1,60,Alive
1,50,2,1,1,1,2,0,2,1,35,1,1,14,5,62,Alive
2,58,2,0,2,2,4,0,2,1,63,1,1,14,7,75,Alive
3,58,2,1,0,0,0,1,3,1,18,1,1,2,1,84,Alive
4,47,2,1,1,0,1,1,3,1,41,1,1,3,1,50,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,1,1,0,0,0,0,2,1,9,1,1,1,1,49,Alive
4020,56,2,0,1,1,2,0,2,1,46,1,1,14,8,69,Alive
4021,68,2,1,1,0,1,0,2,1,22,1,0,11,3,69,Alive
4022,58,0,0,1,0,1,0,2,1,44,1,1,11,1,72,Alive
4023,46,2,1,1,0,1,0,2,1,30,1,1,7,2,100,Alive

In [46]:
df_1['Status'] = lab_enc.fit_transform(df_1['Status'])
df_1

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,2,1,0,0,0,1,3,1,4,1,1,24,1,60,0
1,50,2,1,1,1,2,0,2,1,35,1,1,14,5,62,0
2,58,2,0,2,2,4,0,2,1,63,1,1,14,7,75,0
3,58,2,1,0,0,0,1,3,1,18,1,1,2,1,84,0
4,47,2,1,1,0,1,1,3,1,41,1,1,3,1,50,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,1,1,0,0,0,0,2,1,9,1,1,1,1,49,0
4020,56,2,0,1,1,2,0,2,1,46,1,1,14,8,69,0
4021,68,2,1,1,0,1,0,2,1,22,1,0,11,3,69,0
4022,58,0,0,1,0,1,0,2,1,44,1,1,11,1,72,0
4023,46,2,1,1,0,1,0,2,1,30,1,1,7,2,100,0

In [49]:
df_1['Grade'] = lab_enc.fit_transform(df_1['Grade'])
df_1.dtypes

Age                       int64
Race                      int32
Marital Status            int32
T Stage                   int32
N Stage                   int32
6th Stage                 int32
differentiate             int64
Grade                     int64
A Stage                   int64
Tumor Size                int64
Estrogen Status           int32
Progesterone Status       int32
Regional Node Examined    int64
Reginol Node Positive     int64
Survival Months           int64
Status                    int32
dtype: object

In [50]:
df_1.isnull().sum()

Age                       0
Race                      0
Marital Status            0
T Stage                   0
N Stage                   0
6th Stage                 0
differentiate             0
Grade                     0
A Stage                   0
Tumor Size                0
Estrogen Status           0
Progesterone Status       0
Regional Node Examined    0
Reginol Node Positive     0
Survival Months           0
Status                    0
dtype: int64

In [60]:
x = df_1.iloc[:,:-1].values
x

array([[ 68,   2,   1, ...,  24,   1,  60],
       [ 50,   2,   1, ...,  14,   5,  62],
       [ 58,   2,   0, ...,  14,   7,  75],
       ...,
       [ 68,   2,   1, ...,  11,   3,  69],
       [ 58,   0,   0, ...,  11,   1,  72],
       [ 46,   2,   1, ...,   7,   2, 100]], dtype=int64)

In [61]:
y = df_1.iloc[:,-1].values
y

array([0, 0, 0, ..., 0, 0, 0])

In [62]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)

In [63]:
x_train

array([[ 62,   2,   1, ...,  18,   6,  67],
       [ 55,   2,   3, ...,  13,  10,  53],
       [ 49,   2,   1, ...,   6,   1,  56],
       ...,
       [ 57,   2,   3, ...,  31,   2,  45],
       [ 48,   1,   1, ...,  27,   1, 102],
       [ 53,   2,   1, ...,  14,   2, 104]], dtype=int64)

In [64]:
x_test

array([[45,  2,  1, ..., 24,  1, 80],
       [61,  2,  1, ...,  8,  1, 48],
       [61,  2,  1, ..., 32,  5, 61],
       ...,
       [68,  2,  1, ...,  2,  2, 68],
       [53,  2,  2, ...,  1,  1,  4],
       [61,  0,  3, ..., 12,  3, 40]], dtype=int64)

In [65]:
y_train

array([0, 0, 0, ..., 1, 0, 0])

In [66]:
y_test

array([0, 0, 0, ..., 0, 0, 1])

In [69]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [71]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 1, 1])

In [77]:
from sklearn.metrics import accuracy_score

In [78]:
accuracy = accuracy_score(y_test, y_pred)
accuracy * 100

85.76158940397352

In [96]:
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred)
conf_mat

array([[934,  99],
       [ 73, 102]], dtype=int64)

In [81]:
from sklearn.metrics import precision_score, recall_score
precision = precision_score(y_test, y_pred)
precision*100

50.74626865671642

In [82]:
recall = recall_score(y_test, y_pred)
recall*100

58.285714285714285

In [97]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_pred, output_dict=True)

report_df = pd.DataFrame(report).transpose()

print(report_df)

              precision    recall  f1-score      support
0              0.927507  0.904163  0.915686  1033.000000
1              0.507463  0.582857  0.542553   175.000000
accuracy       0.857616  0.857616  0.857616     0.857616
macro avg      0.717485  0.743510  0.729120  1208.000000
weighted avg   0.866657  0.857616  0.861631  1208.000000